spring:
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 120.79.163.227:9949
        username: nacos
        password: nacos
      config:
        server-addr: 120.79.163.227:9949
        username: nacos
        password: nacos
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.163.227:3306/boss-user?useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: JRFsr0503.
  redis:
    host: 120.79.163.227
    port: 7369
    password: 19970503
    task:
      execution:
        pool:
          core-size: 8
          max-size: 256
          keep-alive: 60000
          queue-capacity: 256
        thread-name-prefix: user-service-task-
  #rabbitmq:
    #host: 192.168.1.32
    #port: 5672
    #username: admin
    #password: admin
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost
