spring:
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: be6ce011-8cf0-452d-934d-7db943424893
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: be6ce011-8cf0-452d-934d-7db943424893
  redis:
    host: localhost
    port: 6379
    password: lanlinker789***
    task:
      execution:
        pool:
          core-size: 8
          max-size: 256
          keep-alive: 60000
          queue-capacity: 256
        thread-name-prefix: user-service-task-
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost
