spring:
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: be6ce011-8cf0-452d-934d-7db943424893
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: be6ce011-8cf0-452d-934d-7db943424893
  redis:
    host: localhost
    port: 6379
    password: lanlinker789***
    task:
      execution:
        pool:
          core-size: 8
          max-size: 256
          keep-alive: 60000
          queue-capacity: 256
        thread-name-prefix: user-service-task-

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://localhost:20300/xxl-job-admin
    executor:
      appname: boss-job-jrf
      address:
      ip:
      port: 20400
      logpath:
      logretentiondays: 30
